user_agent = 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'
instagram_cookies_path = 'instagram_cookies.json'
database_url = ''
database_user = ''
database_password = ''
instagram_login_page = 'https://www.instagram.com/accounts/login/'
instagram_username = ''
instagram_password = ''
instagram_url = 'https://www.instagram.com'

targit_list = 'https://www.instagram.com/fashion/'
